---
title: "Viz_Part1"
author: "Jesus Luevano"
date: "2023-10-01"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)
```

Get the data for plotting

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(  #rnoa pulls in specific dataset from weather
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode( #can also consider case_match or case_when
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10, #to make whoel degree Celsius
    tmax = tmax / 10) |>
  select(name, id, everything())
```


Let's make a plkot 
```{r}
ggplot(weather_df, aes(x = tmin, y= tmax)) + #input data, assign axis (but doesn't pull in how to plot)
       geom_point() #decide to give each datapoint a point on plot

weather_df %>% # can pipe in from dyplr
  ggplot(aes(x = tmin, y = tmax)) + geom_point()

weather_df %>% # can pipe in from dyplr
  filter(name == "CentralPark_NY") %>%
  ggplot(aes(x = tmin, y = tmax)) + geom_point()

#save as varibale
ggp_nycweather =
  weather_df %>% 
  filter(name == "CentralPark_NY") %>%
  ggplot(aes(x = tmin, y = tmax)) + geom_point()

```


## Fancy plot tools

```{r}

```

