---
title: "viz_part2"
author: "Jesus Luevano"
date: "2023-10-03"
output: github_document
---


```{r}
library(tidyverse)
library(ggridges)

#Options to set figure wedith/sets for WHOLE RMD
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6, #keep same ratio based on above width
  out.width = "90%" #take up 90% width of html doc
)
```

Get the data for plotting

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(  #rnoa pulls in specific dataset from weather
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode( #can also consider case_match or case_when
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10, #to make whoel degree Celsius
    tmax = tmax / 10) |>
  select(name, id, everything())
```

## Same plot from last time

```{r}
weather_df %>%
  #filter(tmax >= 20, tmax <=30) %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.5) + 
  labs(
    title = "Temperature plot",
    caption = "Max vs min daily temp in three locations; data from rnoaa",
    x = "Min daily temp (C)",
    y = "Max daily temp (C)",
    color = "Location"
  ) + 
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15 C", "0", "15 C")
  ) +
  scale_y_continuous(
    position = "right",
    limits = c(0,30)
  )
```

what about colors...

```{r}
weather_df %>%
  #filter(tmax >= 20, tmax <=30) %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.5) + 
  labs(
    title = "Temperature plot",
    caption = "Max vs min daily temp in three locations; data from rnoaa",
    x = "Min daily temp (C)",
    y = "Max daily temp (C)",
    color = "Location"
  ) + 
  #scale_color_hue(h = c(100,300))
  viridis::scale_color_viridis(discrete = TRUE)
```

